---
name: Build & Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/dependabot.yml'

env:
  PIP_DISABLE_PIP_VERSION_CHECK: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install Python modules
        run: |
          poetry install --without dev
          poetry run pip list

      - name: Test generator.py
        run: |
          poetry run python mtglabels/generator.py --labels-per-sheet 30 --output-dir /tmp ice
